nats:
  servers:
    - ${NATS_URL}
  options:
    name: ${NATS_TIME_SERVER_NAME}
    user_credentials: ${NATS_USER_CREDENTIALS_FILE}
    # verbose: true
    max_outstanding_pings: 5
    ping_interval: 5
    connect_timeout: 2
    # pedantic: true

service:
  instance_id: ${SERVICE_INSTANCE_ID}

app:
  publish_iso8601_time: ${APP_PUBLISH_ISO8601_TIME}
  clock_start_utc: ${APP_CLOCK_START_UTC}
  clock_increment: ${APP_CLOCK_INCREMENT}
  allow_future_time: ${APP_ALLOW_FUTURE_TIME}
  tick_frequency: ${APP_TICK_FREQUENCY}
